#------------------------------------------------------------------------------
# Makefile for CSE 101 Programming Assignment 1
#
# make                   makes Lex
# make ListClient        makes ListClient
# make clean             removes all binaries
# make checkClient       checks ListClient for memory errors
# make checkLex          checks Lex for memory errors
#------------------------------------------------------------------------------

Lex : Lex.o List.o
	gcc -std=c17 -Wall -g -ggdb -Wall -o Lex Lex.o List.o

Lex.o : Lex.c List.h
	gcc -std=c17 -Wall -g -ggdb -c Lex.c

ListClient: ListClient.o List.o
	gcc -std=c17 -Wall -g -ggdb -o ListClient ListClient.o List.o

ListClient.o : ListClient.c List.h
	gcc -std=c17 -Wall -g -ggdb -c ListClient.c

List.o : List.c List.h
	gcc -std=c17 -Wall -g -ggdb -c List.c

review.o: review.c List.h
	gcc -std=c17 -Wall -g -ggdb -c review.c List.h
clean :
	rm -f Lex ListClient Lex.o ListClient.o List.o

checkClient : 
	valgrind --leak-check=full ListClient

checkLex :
	valgrind --leak-check=full --show-leak-kinds=all ./Lex input.txt output.txt


